steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cn2021-steam-reviews/reviews-svc', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cn2021-steam-reviews/reviews-svc']